name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read

    # 🔹 Variáveis de ambiente que serão injetadas no build do Vite
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      # 1️⃣ Clonar repositório
      - uses: actions/checkout@v3

      # 2️⃣ Instalar dependências
      - name: Install dependencies
        run: npm ci

      # 3️⃣ Build do app Vite + React
      - name: Build app
        run: npm run build

      # 4️⃣ Deploy para Azure Static Web Apps usando Deployment Token
      - name: Deploy to Azure Static Web Apps
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          action: "upload"
          app_location: "/"           # Diretório do código-fonte
          output_location: "dist"     # Diretório de build do Vite

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
