name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    permissions:
      id-token: write
      contents: read

    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_CLIFF_0EA85E90F }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
